import aiClient from "./aiClient";
import EmailAnalysisMail from "../models/emailAnalysisMail.model";

// Strip HTML tags to plain text and truncate.
function toPlain(html = "", maxLen = 1500) {
  const plain = String(html)
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();
  return plain.length > maxLen ? `${plain.slice(0, maxLen)}…` : plain;
}

// Format a thread message for prompt context.
function formatThreadMsg(msg, idx) {
  const from = String(msg.from || "Unknown").slice(0, 200).replace(/\n/g, " ");
  const date = msg.receivedAt ? new Date(msg.receivedAt).toUTCString() : "";
  const body = toPlain(msg.body || msg.snippet || "", 1500);
  return `--- Email ${idx + 1} (${date}) ---\nFrom: ${from}\nSubject: ${msg.subject || "(no subject)"}\n\n${body}`;
}

/**
 * Fetch thread emails in chronological order (oldest first).
 */
async function fetchThreadEmails(mail) {
  const threadKey = mail.provider === "outlook"
    ? { threadId: mail.threadId || mail.providerMessageId }
    : { threadId: mail.threadId };

  if (!mail.threadId) return [mail];

  try {
    const thread = await EmailAnalysisMail.find({
      email: mail.email,
      provider: mail.provider,
      ...threadKey,
      active: true,
    })
      .sort({ receivedAt: 1 })
      .select("from to subject body snippet receivedAt threadId")
      .lean();

    return thread.length > 0 ? thread : [mail];
  } catch {
    return [mail];
  }
}

/**
 * Build the prompt messages for the AI client.
 */
function buildMessages(thread) {
  const system = `You are an elite manufacturing operations executive assistant at a pharmaceutical company.
Your task is to summarize the provided email thread/conversation history.

STRICT RULES:
- Write a concise, high-level summary of the discussion.
- Focus on the core issues, key decisions made, and outstanding action items.
- Structure your output as:
  1. A brief overview paragraph summarizing the context and current state of the conversation (max 3 sentences).
  2. A bulleted list outlining major decisions or milestones reached (prefixed with "✓").
  3. A bulleted list outlining pending action items, questions, or next steps (prefixed with "⚡").
- Return the summary in clean HTML: use <p> for paragraphs, <ul> and <li> for bullet lists.
- Do NOT include <html>, <head>, <body>, or markdown code blocks like \`\`\`html. Keep it under 250 words.`;

  const threadContent = thread.map(formatThreadMsg).join("\n\n");

  const user = `Here is the email thread conversation (oldest first):\n\n${threadContent}\n\nProvide the thread summary now:`;

  return [
    { role: "system", content: system },
    { role: "user", content: user },
  ];
}

/**
 * Generate and cache a conversation summary.
 *
 * @param {Object} mail - Mongoose or lean mail document.
 * @returns {Promise<string>} The generated HTML summary.
 */
export async function generateConversationSummary(mail) {
  const thread = await fetchThreadEmails(mail);
  const messages = buildMessages(thread);

  const rawSummary = await aiClient.chatCompletion(messages);
  let summary = String(rawSummary || "").trim();

  // Strip common markdown block markers if generated by mistake.
  summary = summary
    .replace(/^```html\s*/i, "")
    .replace(/```$/, "")
    .trim();

  if (!summary) {
    throw new Error("AI returned an empty summary.");
  }

  // Cache the summary on all emails in this thread to speed up future requests.
  const threadKey = mail.provider === "outlook"
    ? { threadId: mail.threadId || mail.providerMessageId }
    : { threadId: mail.threadId };

  if (mail.threadId) {
    await EmailAnalysisMail.updateMany(
      {
        email: mail.email,
        provider: mail.provider,
        ...threadKey,
      },
      { $set: { threadSummary: summary } }
    );
  } else {
    await EmailAnalysisMail.updateOne(
      { _id: mail._id },
      { $set: { threadSummary: summary } }
    );
  }

  return summary;
}

export default { generateConversationSummary };
